sudo: required
  services: 
    - docker

before_install:
  - docker build -t alessandro86495/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true alessandro86495/docker-react npm run test